name: Build

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.3.1'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: index-user-js
        path: dist/index.user.js
        artifact-content-type: 'text/javascript'
